### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by MyGodIsHe** [MyGodIsHe/iko#5]
CI for py35-38, pypy?. Run tests, coverage and flake8.

**Comment by MyGodIsHe** [comment]
Example - https://github.com/MyGodIsHe/pytest-neo

Core files:
* .coveragerc
* .travis.yml
* conftest.py
* tox.ini

**Comment by pollydrag** [comment]
Base: https://github.com/MyGodIsHe/iko/pull/8
